spring:
  application.name: wait-times-server
  main.banner-mode: off
  output.ansi.enabled: always
  flyway.clean-on-validation-error: true
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/wait-times

management:
  endpoint.health:
    enabled: true
    show-details: always
  auditevents.enabled: true
  endpoints.web.exposure.include: '*'
server:
  http2.enabled: true
  compression.enabled: true

sms:
  sid: ${SECRET_SMS_SID}
  token: ${SECRET_SMS_TOKEN}
  numbers:
    from: ${SECRET_SMS_NUMBERS_FROM}
    to: ${SECRET_SMS_NUMBERS_TO}

rides:
  notification-threshold-minutes: 20
  preferred:
    - "Space Mountain"
    - "Incredicoaster"
    - "Haunted Mansion"
    - "Splash Mountain"
    - "Grizzly River Run"
    - "Goofy's Sky School"
    - "Hyperspace Mountain"
    - "Matterhorn Bobsleds"
    - "Alice in Wonderland"
    - "Radiator Springs Racers"
    - "Toy Story Midway Mania!"
    - "Indiana Jones™ Adventure"
    - "Pirates of the Caribbean"
    - "Soarin' Around the World"
    - "Big Thunder Mountain Railroad"
    - "Millennium Falcon: Smugglers Run"
    - "Star Tours – The Adventures Continue"
    - "Guardians of the Galaxy – Mission: BREAKOUT!"
