apiVersion: v1
kind: Service
metadata:
  name: wait-times-server-service
  namespace: wait-times
  labels:
    app: wait-times-server
spec:
  type: NodePort
  selector:
    app: wait-times-server
  ports:
    - port: 80
      targetPort: 8080
